### ISSUE TITLE
Best way to parse response after fetch()

### ISSUE THREAD

**Issue by miguelrk** [yamlscript/yamlscript#2]
I've been playing around with yamlscript after some time using denoflow, and I'm not sure how one can go about parsing the response of a fetch() call in the best way e.g. doing `await response.json()` after

```yaml
- use: fetch
  args: https://actionsflow.github.io/test-page/reddit-sample.json
```

Some alternatives that come to mind are using 

```yaml
- use: eval
  args: "result = await result.json"
```

But it is not working since eval does not have an implicit return. Using a third party http client which auto-parses the response could work, but I'd like to keep it simple with fetch().

In denoflow there was a `run` field which came handy for running stuff after each step. Is this something that would also fit to the scope of this project. Or am I missing something and running arbitraty code e.g. for parsing response is alreafy possible?

Thanks in advanced!

**Comment by theowenyoung** [comment]
Well, yamlscript is designed to write it simply, so in this case it will be:

```yaml
- id: response
  use: fetch
  args: https://actionsflow.github.io/test-page/reddit-sample.json
- id: json
  use: response.json
- use: console.log
  args: $json
```
